// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hienv_asp.Context;

#nullable disable

namespace hienv_asp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230808041846_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hienv_asp.Models.CategoriesDescription", b =>
                {
                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("language_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meta_description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("meta_keyword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("name")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("category_id", "language_id");

                    b.HasIndex(new[] { "name" }, "idx_categories_name_zen");

                    b.ToTable("category_description");
                });

            modelBuilder.Entity("hienv_asp.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("category_id"));

                    b.Property<int>("column")
                        .HasColumnType("int");

                    b.Property<DateTime?>("date_added")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("date_modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("parent_id")
                        .HasColumnType("int");

                    b.Property<int?>("sort_order")
                        .HasColumnType("int");

                    b.Property<short>("status")
                        .HasColumnType("smallint");

                    b.Property<int>("top")
                        .HasColumnType("int");

                    b.HasKey("category_id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("hienv_asp.Models.CategoryToLayout", b =>
                {
                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("store_id")
                        .HasColumnType("int");

                    b.Property<int>("layout_id")
                        .HasColumnType("int");

                    b.HasKey("category_id", "store_id");

                    b.ToTable("category_to_layout");
                });

            modelBuilder.Entity("hienv_asp.Models.CategoryToStore", b =>
                {
                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("store_id")
                        .HasColumnType("int");

                    b.HasKey("category_id", "store_id");

                    b.ToTable("category_to_store");
                });

            modelBuilder.Entity("hienv_asp.Models.ErrorViewModel", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ErrorViewModel");
                });
#pragma warning restore 612, 618
        }
    }
}
